name: Publish release
on:
  workflow_dispatch:
#  push:
#    tags:
#      - "*.*.*"
permissions:
  contents: write
env:
  DOTNET_VERSION: "7.0.x"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # history is required for finding version tags

      - name: Set executable permission for scripts
        shell: bash
        run: chmod u+x *.sh

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build application
        shell: bash
        run: ./build.sh

      - name: Create release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            publish/*.zip
            publish/*.tar.gz
          fail_on_unmatched_files: true
          #token: ${{ secrets.GITHUB_TOKEN }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
